### PR TITLE
added nonce check

### PR DESCRIPTION
**Pull request by kazuakiishiguro**
## Description

added nonce check

## Is this PR related with an open issue?
no

Related to Issue #
no

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Follows the code style of this project.
- [x] Tests Cover Changes

### CODE REVIEW

**Comment by kazuakiishiguro** [comment]
added `function bytes32ToString(bytes32 x) public pure returns (string memory) {}` method

**Comment by hrntknr** [comment]
killallってどこで実行されてます？
https://travis-ci.org/connectometo/marketplace-mvp/jobs/517032126#L2035

**Comment by kazuakiishiguro** [comment]
```
"scripts": {
    "ganache": "ganache-cli --networkId 50146",
    "migrate": "rm -rf build && npx truffle migrate --reset",
    "test": "npm run ganache & npm run test:solium && npm run test:truffle && npm run exit",
    "test:coverage": "./node_modules/.bin/solidity-coverage",
    "test:solium": "solium -d contracts/",
    "test:truffle": "npx truffle compile --reset && npx truffle test",
    "exit": "killall node"
  },
```
最後exitでganacheのプロセス落としてますが、これ要らなさそうですかね？

**Comment by kazuakiishiguro** [comment]
changed `npm run exit` script

```
 "exit": "lsof -i :8545 | grep node | grep -v grep | awk '{ print \"kill -9\", $2 }' | sh"
```

**Comment by kazuakiishiguro** [comment]
again, removed `npm run exit` command from `npm run test` since travis exit with error log.

**Pull request merged**
